### ISSUE TITLE
Make Contact Us

### ISSUE THREAD

**Issue by NeoAnoman** [NeoAnoman/NssWeb#2]
Contact us component is needed in the website so this should be made ASAP...

**Comment by Sonal240** [comment]
I have done my work. Please review it ASAP

**Comment by NeoAnoman** [comment]
I have checked the work...there is minor editing I will do and before closing this issue I want you to give me the list of all dependencies that are required here to execute the code...

**Comment by NeoAnoman** [comment]
mail me the file package-lock and package.json at neoanoman@gmail.com

**Comment by NeoAnoman** [comment]
also upload the images that are required for working of the webpage....

**Comment by Sonal240** [comment]
[nss_img.zip](https://github.com/NeoAnoman/NssWeb/files/3520829/nss_img.zip)

[contact_page.zip](https://github.com/NeoAnoman/NssWeb/files/3520834/contact_page.zip)

**Comment by Sonal240** [comment]
New images are added in header of contact page, footer is not yet updated but it will be uploaded by latest this evening

**Comment by Sonal240** [comment]
In header use NSS_POSTER, nss_img_6 and nss_img_5 for slideshow

**Comment by NeoAnoman** [comment]
please keep fetching the files since I am updating them regularly....

**Comment by NeoAnoman** [comment]
> [nss_img.zip](https://github.com/NeoAnoman/NssWeb/files/3520829/nss_img.zip)
> 
> [contact_page.zip](https://github.com/NeoAnoman/NssWeb/files/3520834/contact_page.zip)

please from next time add the files by pushing them in repository...

**Comment by NeoAnoman** [comment]
Thanks for your contribution
