### ISSUE TITLE
Activities page

### ISSUE THREAD

**Issue by NeoAnoman** [NeoAnoman/NssWeb#4]
Someone make activity page and upload it in components folder.

**Comment by Sonal240** [comment]
Added activity page to it
Read the comments and make necessary changes

**Comment by NeoAnoman** [comment]
I have made some changes but there are still some problems there...

**Comment by NeoAnoman** [comment]
please update your leaf branch with current version of website....and make changes in there.

**Comment by NeoAnoman** [comment]
Report me ASAP.

**Comment by NeoAnoman** [comment]
I am merging master to your branch to update it's codes present in it please keep updating your branch regularly before collaborating...and keep up the good work..

**Comment by NeoAnoman** [comment]
Please mention here when you upload your work...
